// Generated by LiveScript 1.6.0
(function(){
  var request, getStockInfo;
  request = require('request');
  getStockInfo = function(stockId, cb){
    var option;
    option = {
      url: "https://goodinfo.tw/StockInfo/ShowK_Chart.asp?STOCK_ID=" + stockId + "&CHT_CAT2=DATE",
      method: "GET"
    };
    return request(option, function(err, res, body){
      return cb(err, body);
    });
  };
  getStockInfo(2331, function(err, res){
    console.log(err);
    return console.log(res);
  });
}).call(this);
