// Generated by LiveScript 1.6.0
(function(){
  var WebSocket, pako, x$, huobiWs;
  WebSocket = require('ws');
  pako = require('pako');
  /*
  binanceWs = new WebSocket 'wss://stream.binance.com:9443/ws/btcusdt@depth10'
      ..on 'open', ->
          console.log 'open'
  
      ..on 'close', ->
          console.log 'close'
      
      ..on 'message', (data) ->
          console.log JSON.parse(data)
          
      ..on 'error', (err) ->
          console.log err
  
  */
  x$ = huobiWs = new WebSocket('wss://api.huobi.pro/ws');
  x$.on('open', function(){
    var sendData;
    console.log('open');
    sendData = JSON.stringify({
      sub: 'market.btcusdt.depth.step0',
      id: 'xx20'
    });
    return huobiWs.send(sendData, function(err){
      return console.log(err);
    });
  });
  x$.on('close', function(){
    return console.log('close');
  });
  x$.on('message', function(buf){
    var data, ping, sendData, ref$, bids, asks;
    data = JSON.parse(pako.inflate(buf, {
      to: 'string'
    }));
    if (!!data["ping"]) {
      ping = data.ping;
      sendData = JSON.stringify({
        pong: ping
      });
      huobiWs.send(sendData, function(err){
        return console.log(err);
      });
    }
    if (data['ch'] === 'market.btcusdt.depth.step0') {
      ref$ = data.tick, bids = ref$.bids, asks = ref$.asks;
      return console.log(bids);
    }
  });
  x$.on('error', function(err){
    return console.log(err);
  });
}).call(this);
