// Generated by LiveScript 1.6.0
(function(){
  var request, crypto, moment, Tool;
  request = require('request');
  crypto = require('crypto');
  moment = require('moment');
  Tool = require('./brickpicker/tool');
  Tool.getUrl(Tool.huobiSignedOption("api.huobipro.com", "/v1/account/accounts", {}, "GET"), function(err, res){
    var info, account_id;
    console.log(res);
    info = JSON.parse(res);
    console.log(info);
    if (info.status === "ok") {
      account_id = info.data[0].id;
      Tool.getUrl(Tool.huobiSignedOption("api.huobipro.com", "/v1/order/orders/place", {
        "account-id": account_id,
        type: "buy-limit",
        amount: 1,
        symbol: "btcusdt",
        price: 1
      }, "POST"), function(err, res){
        return console.log(res);
      });
    }
    return Tool.getUrl(Tool.huobiSignedOption("api.huobipro.com", "/v1/order/orders", {
      symbol: "btcusdt",
      states: "submitted,partial-filled"
    }, "GET"), function(err, res){
      return console.log(res);
    });
  });
}).call(this);
