// Generated by LiveScript 1.6.0
(function(){
  var express, path, request, async, crypto, fs, fetch, getUrl, app, slice$ = [].slice;
  express = require('express');
  path = require('path');
  request = require('request');
  async = require('async');
  crypto = require('crypto');
  fs = require('fs');
  fetch = function(url, dontUseCache){
    return new Promise(function(res, rej){
      var urlKey, path;
      urlKey = crypto.createHash('md5').update(url).digest('hex');
      path = "cache/" + urlKey + ".html";
      if (!!dontUseCache === false) {
        if (fs.existsSync(path)) {
          return fs.readFile(path, 'utf8', function(err, info){
            if (err) {
              return rej(err);
            } else {
              return res(info);
            }
          });
        } else {
          return request.get(url).on('error', function(err){
            return rej(err);
          }).on('end', function(){
            if (fs.existsSync(path) === false) {
              return rej('save lost');
            } else {
              return fs.readFile(path, 'utf8', function(err, info){
                if (err) {
                  return rej(err);
                } else {
                  return res(info);
                }
              });
            }
          }).pipe(fs.createWriteStream(path));
        }
      }
    });
  };
  getUrl = curry$(function(url, cb){
    var options, callback;
    console.log(url);
    options = {
      url: url,
      method: 'GET',
      headers: {
        'User-Agent': 'request'
      }
    };
    callback = function(error, response, body){
      if (error) {
        return cb(error);
      } else {
        return cb(null, JSON.parse(body));
      }
    };
    return request(options, callback);
  });
  app = express();
  app.set('port', 8080);
  app.set('views', path.join(__dirname, '/views'));
  app.set('view engine', 'vash');
  app.get('/view/stock/:cnt/:stockId', function(req, res){
    var stockId, cnt, callPromise;
    stockId = req.params.stockId;
    cnt = parseInt(req.params.cnt);
    callPromise = curry$(function(url, cb){
      return fetch(url, false)['catch'](function(err){
        return cb(err);
      }).then(function(res){
        return cb(null, res);
      });
    });
    return async.series((function(){
      var i$, to$, results$ = [];
      for (i$ = 1, to$ = cnt; i$ <= to$; ++i$) {
        results$.push(i$);
      }
      return results$;
    }()).map(function(m){
      return callPromise("http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=2017" + (m + '').padStart(2, '0') + "01&stockNo=" + stockId);
    }), function(err, results){
      var data, format, e;
      if (err) {
        return res.json(err);
      } else {
        try {
          data = results.filter(function(r){
            return r.trim() !== "";
          }).map(JSON.parse).reduce(function(acc, arg$){
            var data;
            data = arg$.data;
            return acc.concat(data);
          }, []);
          format = function(arg$){
            var openTime, _, _2, open, high, low, close;
            openTime = arg$[0], _ = arg$[1], _2 = arg$[2], open = arg$[3], high = arg$[4], low = arg$[5], close = arg$[6];
            return [new Date(openTime).toString()].concat([low, open, close, high].map(parseFloat));
          };
          data = JSON.stringify(partialize$.apply(Array.prototype.map, [Array.prototype.map.call, [void 8, format], [0]])(
          data));
          return res.render("kline", {
            data: data
          });
        } catch (e$) {
          e = e$;
          return res.json(results);
        }
      }
    });
  });
  app.get('/view/kline/:ma/:mb/:range/:count', function(req, res){
    var count, ma, mb, range;
    count = req.params.count;
    ma = req.params.ma;
    mb = req.params.mb;
    range = req.params.range;
    return getUrl(("https://api.binance.com/api/v1/klines?interval=" + range + "&limit=" + count + "&symbol=") + mb.toUpperCase() + ma.toUpperCase(), function(err, data){
      var format;
      if (err) {
        return res.render('error');
      } else {
        format = function(arg$){
          var openTime, open, high, low, close;
          openTime = arg$[0], open = arg$[1], high = arg$[2], low = arg$[3], close = arg$[4];
          return [new Date(openTime).toString()].concat([low, open, close, high].map(parseFloat));
        };
        data = JSON.stringify(partialize$.apply(Array.prototype.map, [Array.prototype.map.call, [void 8, format], [0]])(
        data));
        return res.render("kline", {
          data: data
        });
      }
    });
  });
  app.get('/', function(req, res){
    return res.render('index', {
      title: "[['Mon', 20, 28, 38, 45]]",
      data: "[['Mon', 20, 28, 38, 45],['Tue', 31, 38, 55, 66],['Wed', 50, 55, 77, 80],['Thu', 77, 77, 66, 50],['Fri', 68, 66, 22, 15]]"
    });
  });
  app.listen(8080);
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
  function partialize$(f, args, where){
    var context = this;
    return function(){
      var params = slice$.call(arguments), i,
          len = params.length, wlen = where.length,
          ta = args ? args.concat() : [], tw = where ? where.concat() : [];
      for(i = 0; i < len; ++i) { ta[tw[0]] = params[i]; tw.shift(); }
      return len < wlen && len ?
        partialize$.apply(context, [f, ta, tw]) : f.apply(context, ta);
    };
  }
}).call(this);
