using UnityEngine;
namespace Remix{
	public class LevelNoteCht{
		public const int ID_COUNT = 167;

		public string StageId {get; set;}
public string Name {get; set;}
public string TextGameMode {get; set;}
public string TextArtistTitle {get; set;}
public string TextSongTitle {get; set;}

		public static LevelNoteCht Get(string key){
			switch (key) {
			case "Map01_00n": return new LevelNoteCht{StageId="Map01_00n",Name="Tutorial",TextGameMode="Tutorial"};
case "Map01_0An": return new LevelNoteCht{StageId="Map01_0An",Name="SYNC",TextGameMode="SYNC"};
case "Map01_01e": return new LevelNoteCht{StageId="Map01_01e",Name="猴硐 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_01n": return new LevelNoteCht{StageId="Map01_01n",Name="猴硐 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_01h": return new LevelNoteCht{StageId="Map01_01h",Name="猴硐 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_02e": return new LevelNoteCht{StageId="Map01_02e",Name="猴硐 關卡 02",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_02n": return new LevelNoteCht{StageId="Map01_02n",Name="猴硐 關卡 02",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_02h": return new LevelNoteCht{StageId="Map01_02h",Name="猴硐 關卡 02",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_03e": return new LevelNoteCht{StageId="Map01_03e",Name="猴硐 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_03n": return new LevelNoteCht{StageId="Map01_03n",Name="猴硐 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_03h": return new LevelNoteCht{StageId="Map01_03h",Name="猴硐 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_04e": return new LevelNoteCht{StageId="Map01_04e",Name="猴硐 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_04n": return new LevelNoteCht{StageId="Map01_04n",Name="猴硐 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_04h": return new LevelNoteCht{StageId="Map01_04h",Name="猴硐 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_05e": return new LevelNoteCht{StageId="Map01_05e",Name="猴硐 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_05n": return new LevelNoteCht{StageId="Map01_05n",Name="猴硐 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_05h": return new LevelNoteCht{StageId="Map01_05h",Name="猴硐 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_06e": return new LevelNoteCht{StageId="Map01_06e",Name="猴硐 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_06n": return new LevelNoteCht{StageId="Map01_06n",Name="猴硐 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_06h": return new LevelNoteCht{StageId="Map01_06h",Name="猴硐 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_07e": return new LevelNoteCht{StageId="Map01_07e",Name="猴硐 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_07n": return new LevelNoteCht{StageId="Map01_07n",Name="猴硐 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_07h": return new LevelNoteCht{StageId="Map01_07h",Name="猴硐 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_08e": return new LevelNoteCht{StageId="Map01_08e",Name="猴硐 關卡 08",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_08n": return new LevelNoteCht{StageId="Map01_08n",Name="猴硐 關卡 08",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_08h": return new LevelNoteCht{StageId="Map01_08h",Name="猴硐 關卡 08",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_09e": return new LevelNoteCht{StageId="Map01_09e",Name="猴硐 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_09n": return new LevelNoteCht{StageId="Map01_09n",Name="猴硐 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_09h": return new LevelNoteCht{StageId="Map01_09h",Name="猴硐 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_10e": return new LevelNoteCht{StageId="Map01_10e",Name="猴硐 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case "Map01_10n": return new LevelNoteCht{StageId="Map01_10n",Name="猴硐 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case "Map01_10h": return new LevelNoteCht{StageId="Map01_10h",Name="猴硐 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case "Map02_01e": return new LevelNoteCht{StageId="Map02_01e",Name="座間味 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_01n": return new LevelNoteCht{StageId="Map02_01n",Name="座間味 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_01h": return new LevelNoteCht{StageId="Map02_01h",Name="座間味 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_02e": return new LevelNoteCht{StageId="Map02_02e",Name="座間味 關卡 02",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_02n": return new LevelNoteCht{StageId="Map02_02n",Name="座間味 關卡 02",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_02h": return new LevelNoteCht{StageId="Map02_02h",Name="座間味 關卡 02",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_03e": return new LevelNoteCht{StageId="Map02_03e",Name="座間味 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_03n": return new LevelNoteCht{StageId="Map02_03n",Name="座間味 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_03h": return new LevelNoteCht{StageId="Map02_03h",Name="座間味 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case "Map02_04e": return new LevelNoteCht{StageId="Map02_04e",Name="座間味 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_04n": return new LevelNoteCht{StageId="Map02_04n",Name="座間味 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_04h": return new LevelNoteCht{StageId="Map02_04h",Name="座間味 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_05e": return new LevelNoteCht{StageId="Map02_05e",Name="座間味 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_05n": return new LevelNoteCht{StageId="Map02_05n",Name="座間味 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_05h": return new LevelNoteCht{StageId="Map02_05h",Name="座間味 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_06e": return new LevelNoteCht{StageId="Map02_06e",Name="座間味 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_06n": return new LevelNoteCht{StageId="Map02_06n",Name="座間味 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_06h": return new LevelNoteCht{StageId="Map02_06h",Name="座間味 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case "Map02_07e": return new LevelNoteCht{StageId="Map02_07e",Name="座間味 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_07n": return new LevelNoteCht{StageId="Map02_07n",Name="座間味 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_07h": return new LevelNoteCht{StageId="Map02_07h",Name="座間味 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_08e": return new LevelNoteCht{StageId="Map02_08e",Name="座間味 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_08n": return new LevelNoteCht{StageId="Map02_08n",Name="座間味 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_08h": return new LevelNoteCht{StageId="Map02_08h",Name="座間味 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_09e": return new LevelNoteCht{StageId="Map02_09e",Name="座間味 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_09n": return new LevelNoteCht{StageId="Map02_09n",Name="座間味 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_09h": return new LevelNoteCht{StageId="Map02_09h",Name="座間味 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case "Map02_10e": return new LevelNoteCht{StageId="Map02_10e",Name="座間味 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="情緒來了"};
case "Map02_10n": return new LevelNoteCht{StageId="Map02_10n",Name="座間味 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="情緒來了"};
case "Map02_10h": return new LevelNoteCht{StageId="Map02_10h",Name="座間味 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="情緒來了"};
case "Map03_01e": return new LevelNoteCht{StageId="Map03_01e",Name="渡嘉敷 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_01n": return new LevelNoteCht{StageId="Map03_01n",Name="渡嘉敷 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_01h": return new LevelNoteCht{StageId="Map03_01h",Name="渡嘉敷 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_02e": return new LevelNoteCht{StageId="Map03_02e",Name="渡嘉敷 關卡 02",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_02n": return new LevelNoteCht{StageId="Map03_02n",Name="渡嘉敷 關卡 02",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_02h": return new LevelNoteCht{StageId="Map03_02h",Name="渡嘉敷 關卡 02",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_03e": return new LevelNoteCht{StageId="Map03_03e",Name="渡嘉敷 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_03n": return new LevelNoteCht{StageId="Map03_03n",Name="渡嘉敷 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_03h": return new LevelNoteCht{StageId="Map03_03h",Name="渡嘉敷 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case "Map03_04e": return new LevelNoteCht{StageId="Map03_04e",Name="渡嘉敷 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_04n": return new LevelNoteCht{StageId="Map03_04n",Name="渡嘉敷 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_04h": return new LevelNoteCht{StageId="Map03_04h",Name="渡嘉敷 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_05e": return new LevelNoteCht{StageId="Map03_05e",Name="渡嘉敷 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_05n": return new LevelNoteCht{StageId="Map03_05n",Name="渡嘉敷 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_05h": return new LevelNoteCht{StageId="Map03_05h",Name="渡嘉敷 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_06e": return new LevelNoteCht{StageId="Map03_06e",Name="渡嘉敷 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_06n": return new LevelNoteCht{StageId="Map03_06n",Name="渡嘉敷 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_06h": return new LevelNoteCht{StageId="Map03_06h",Name="渡嘉敷 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_07e": return new LevelNoteCht{StageId="Map03_07e",Name="渡嘉敷 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_07n": return new LevelNoteCht{StageId="Map03_07n",Name="渡嘉敷 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_07h": return new LevelNoteCht{StageId="Map03_07h",Name="渡嘉敷 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_08e": return new LevelNoteCht{StageId="Map03_08e",Name="渡嘉敷 關卡 08",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_08n": return new LevelNoteCht{StageId="Map03_08n",Name="渡嘉敷 關卡 08",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_08h": return new LevelNoteCht{StageId="Map03_08h",Name="渡嘉敷 關卡 08",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_09e": return new LevelNoteCht{StageId="Map03_09e",Name="渡嘉敷 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_09n": return new LevelNoteCht{StageId="Map03_09n",Name="渡嘉敷 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_09h": return new LevelNoteCht{StageId="Map03_09h",Name="渡嘉敷 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case "Map03_10e": return new LevelNoteCht{StageId="Map03_10e",Name="渡嘉敷 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="孥克的詭計"};
case "Map03_10n": return new LevelNoteCht{StageId="Map03_10n",Name="渡嘉敷 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="孥克的詭計"};
case "Map03_10h": return new LevelNoteCht{StageId="Map03_10h",Name="渡嘉敷 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="孥克的詭計"};
case "Map04_01e": return new LevelNoteCht{StageId="Map04_01e",Name="台鹼宿舍 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_01n": return new LevelNoteCht{StageId="Map04_01n",Name="台鹼宿舍 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_01h": return new LevelNoteCht{StageId="Map04_01h",Name="台鹼宿舍 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_02e": return new LevelNoteCht{StageId="Map04_02e",Name="台鹼宿舍 關卡 02",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_02n": return new LevelNoteCht{StageId="Map04_02n",Name="台鹼宿舍 關卡 02",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_02h": return new LevelNoteCht{StageId="Map04_02h",Name="台鹼宿舍 關卡 02",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_03e": return new LevelNoteCht{StageId="Map04_03e",Name="台鹼宿舍 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_03n": return new LevelNoteCht{StageId="Map04_03n",Name="台鹼宿舍 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_03h": return new LevelNoteCht{StageId="Map04_03h",Name="台鹼宿舍 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case "Map04_04e": return new LevelNoteCht{StageId="Map04_04e",Name="台鹼宿舍 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_04n": return new LevelNoteCht{StageId="Map04_04n",Name="台鹼宿舍 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_04h": return new LevelNoteCht{StageId="Map04_04h",Name="台鹼宿舍 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_05e": return new LevelNoteCht{StageId="Map04_05e",Name="台鹼宿舍 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_05n": return new LevelNoteCht{StageId="Map04_05n",Name="台鹼宿舍 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_05h": return new LevelNoteCht{StageId="Map04_05h",Name="台鹼宿舍 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_06e": return new LevelNoteCht{StageId="Map04_06e",Name="台鹼宿舍 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_06n": return new LevelNoteCht{StageId="Map04_06n",Name="台鹼宿舍 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_06h": return new LevelNoteCht{StageId="Map04_06h",Name="台鹼宿舍 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case "Map04_07e": return new LevelNoteCht{StageId="Map04_07e",Name="台鹼宿舍 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_07n": return new LevelNoteCht{StageId="Map04_07n",Name="台鹼宿舍 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_07h": return new LevelNoteCht{StageId="Map04_07h",Name="台鹼宿舍 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_08e": return new LevelNoteCht{StageId="Map04_08e",Name="台鹼宿舍 關卡 08",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_08n": return new LevelNoteCht{StageId="Map04_08n",Name="台鹼宿舍 關卡 08",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_08h": return new LevelNoteCht{StageId="Map04_08h",Name="台鹼宿舍 關卡 08",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_09e": return new LevelNoteCht{StageId="Map04_09e",Name="台鹼宿舍 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_09n": return new LevelNoteCht{StageId="Map04_09n",Name="台鹼宿舍 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_09h": return new LevelNoteCht{StageId="Map04_09h",Name="台鹼宿舍 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case "Map04_10e": return new LevelNoteCht{StageId="Map04_10e",Name="台鹼宿舍 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="真的很真"};
case "Map04_10n": return new LevelNoteCht{StageId="Map04_10n",Name="台鹼宿舍 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="真的很真"};
case "Map04_10h": return new LevelNoteCht{StageId="Map04_10h",Name="台鹼宿舍 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="真的很真"};
case "MapS1_01e": return new LevelNoteCht{StageId="MapS1_01e",Name="澎湖 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_01n": return new LevelNoteCht{StageId="MapS1_01n",Name="澎湖 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_01h": return new LevelNoteCht{StageId="MapS1_01h",Name="澎湖 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_02e": return new LevelNoteCht{StageId="MapS1_02e",Name="澎湖 關卡 02",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_02n": return new LevelNoteCht{StageId="MapS1_02n",Name="澎湖 關卡 02",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_02h": return new LevelNoteCht{StageId="MapS1_02h",Name="澎湖 關卡 02",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_03e": return new LevelNoteCht{StageId="MapS1_03e",Name="澎湖 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_03n": return new LevelNoteCht{StageId="MapS1_03n",Name="澎湖 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_03h": return new LevelNoteCht{StageId="MapS1_03h",Name="澎湖 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case "MapS1_04e": return new LevelNoteCht{StageId="MapS1_04e",Name="澎湖 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_04n": return new LevelNoteCht{StageId="MapS1_04n",Name="澎湖 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_04h": return new LevelNoteCht{StageId="MapS1_04h",Name="澎湖 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_05e": return new LevelNoteCht{StageId="MapS1_05e",Name="澎湖 關卡 05",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_05n": return new LevelNoteCht{StageId="MapS1_05n",Name="澎湖 關卡 05",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_05h": return new LevelNoteCht{StageId="MapS1_05h",Name="澎湖 關卡 05",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_06e": return new LevelNoteCht{StageId="MapS1_06e",Name="澎湖 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_06n": return new LevelNoteCht{StageId="MapS1_06n",Name="澎湖 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_06h": return new LevelNoteCht{StageId="MapS1_06h",Name="澎湖 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case "MapS1_07e": return new LevelNoteCht{StageId="MapS1_07e",Name="澎湖 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_07n": return new LevelNoteCht{StageId="MapS1_07n",Name="澎湖 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_07h": return new LevelNoteCht{StageId="MapS1_07h",Name="澎湖 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_08e": return new LevelNoteCht{StageId="MapS1_08e",Name="澎湖 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_08n": return new LevelNoteCht{StageId="MapS1_08n",Name="澎湖 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_08h": return new LevelNoteCht{StageId="MapS1_08h",Name="澎湖 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_09e": return new LevelNoteCht{StageId="MapS1_09e",Name="澎湖 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_09n": return new LevelNoteCht{StageId="MapS1_09n",Name="澎湖 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_09h": return new LevelNoteCht{StageId="MapS1_09h",Name="澎湖 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case "MapS1_10e": return new LevelNoteCht{StageId="MapS1_10e",Name="澎湖 關卡 10",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_10n": return new LevelNoteCht{StageId="MapS1_10n",Name="澎湖 關卡 10",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_10h": return new LevelNoteCht{StageId="MapS1_10h",Name="澎湖 關卡 10",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_11e": return new LevelNoteCht{StageId="MapS1_11e",Name="澎湖 關卡 11",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_11n": return new LevelNoteCht{StageId="MapS1_11n",Name="澎湖 關卡 11",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_11h": return new LevelNoteCht{StageId="MapS1_11h",Name="澎湖 關卡 11",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_12e": return new LevelNoteCht{StageId="MapS1_12e",Name="澎湖 關卡 12",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_12n": return new LevelNoteCht{StageId="MapS1_12n",Name="澎湖 關卡 12",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_12h": return new LevelNoteCht{StageId="MapS1_12h",Name="澎湖 關卡 12",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case "MapS1_13e": return new LevelNoteCht{StageId="MapS1_13e",Name="澎湖 關卡 13",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_13n": return new LevelNoteCht{StageId="MapS1_13n",Name="澎湖 關卡 13",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_13h": return new LevelNoteCht{StageId="MapS1_13h",Name="澎湖 關卡 13",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_14e": return new LevelNoteCht{StageId="MapS1_14e",Name="澎湖 關卡 14",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_14n": return new LevelNoteCht{StageId="MapS1_14n",Name="澎湖 關卡 14",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_14h": return new LevelNoteCht{StageId="MapS1_14h",Name="澎湖 關卡 14",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_15e": return new LevelNoteCht{StageId="MapS1_15e",Name="澎湖 關卡 15",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_15n": return new LevelNoteCht{StageId="MapS1_15n",Name="澎湖 關卡 15",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case "MapS1_15h": return new LevelNoteCht{StageId="MapS1_15h",Name="澎湖 關卡 15",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};

			default:
				throw new UnityException ("沒有這個定義:"+key);
			}
		}

		public static LevelNoteCht Get(int key){
			switch (key) {
			case 0: return new LevelNoteCht{StageId="Map01_00n",Name="Tutorial",TextGameMode="Tutorial"};
case 1: return new LevelNoteCht{StageId="Map01_0An",Name="SYNC",TextGameMode="SYNC"};
case 2: return new LevelNoteCht{StageId="Map01_01e",Name="猴硐 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 3: return new LevelNoteCht{StageId="Map01_01n",Name="猴硐 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 4: return new LevelNoteCht{StageId="Map01_01h",Name="猴硐 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 5: return new LevelNoteCht{StageId="Map01_02e",Name="猴硐 關卡 02",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 6: return new LevelNoteCht{StageId="Map01_02n",Name="猴硐 關卡 02",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 7: return new LevelNoteCht{StageId="Map01_02h",Name="猴硐 關卡 02",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 8: return new LevelNoteCht{StageId="Map01_03e",Name="猴硐 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 9: return new LevelNoteCht{StageId="Map01_03n",Name="猴硐 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 10: return new LevelNoteCht{StageId="Map01_03h",Name="猴硐 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 11: return new LevelNoteCht{StageId="Map01_04e",Name="猴硐 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 12: return new LevelNoteCht{StageId="Map01_04n",Name="猴硐 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 13: return new LevelNoteCht{StageId="Map01_04h",Name="猴硐 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 14: return new LevelNoteCht{StageId="Map01_05e",Name="猴硐 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 15: return new LevelNoteCht{StageId="Map01_05n",Name="猴硐 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 16: return new LevelNoteCht{StageId="Map01_05h",Name="猴硐 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 17: return new LevelNoteCht{StageId="Map01_06e",Name="猴硐 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 18: return new LevelNoteCht{StageId="Map01_06n",Name="猴硐 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 19: return new LevelNoteCht{StageId="Map01_06h",Name="猴硐 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 20: return new LevelNoteCht{StageId="Map01_07e",Name="猴硐 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 21: return new LevelNoteCht{StageId="Map01_07n",Name="猴硐 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 22: return new LevelNoteCht{StageId="Map01_07h",Name="猴硐 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 23: return new LevelNoteCht{StageId="Map01_08e",Name="猴硐 關卡 08",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 24: return new LevelNoteCht{StageId="Map01_08n",Name="猴硐 關卡 08",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 25: return new LevelNoteCht{StageId="Map01_08h",Name="猴硐 關卡 08",TextGameMode="對戰模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 26: return new LevelNoteCht{StageId="Map01_09e",Name="猴硐 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 27: return new LevelNoteCht{StageId="Map01_09n",Name="猴硐 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 28: return new LevelNoteCht{StageId="Map01_09h",Name="猴硐 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 29: return new LevelNoteCht{StageId="Map01_10e",Name="猴硐 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case 30: return new LevelNoteCht{StageId="Map01_10n",Name="猴硐 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case 31: return new LevelNoteCht{StageId="Map01_10h",Name="猴硐 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case 32: return new LevelNoteCht{StageId="Map02_01e",Name="座間味 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 33: return new LevelNoteCht{StageId="Map02_01n",Name="座間味 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 34: return new LevelNoteCht{StageId="Map02_01h",Name="座間味 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 35: return new LevelNoteCht{StageId="Map02_02e",Name="座間味 關卡 02",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 36: return new LevelNoteCht{StageId="Map02_02n",Name="座間味 關卡 02",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 37: return new LevelNoteCht{StageId="Map02_02h",Name="座間味 關卡 02",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 38: return new LevelNoteCht{StageId="Map02_03e",Name="座間味 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 39: return new LevelNoteCht{StageId="Map02_03n",Name="座間味 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 40: return new LevelNoteCht{StageId="Map02_03h",Name="座間味 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="全壘打"};
case 41: return new LevelNoteCht{StageId="Map02_04e",Name="座間味 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 42: return new LevelNoteCht{StageId="Map02_04n",Name="座間味 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 43: return new LevelNoteCht{StageId="Map02_04h",Name="座間味 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 44: return new LevelNoteCht{StageId="Map02_05e",Name="座間味 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 45: return new LevelNoteCht{StageId="Map02_05n",Name="座間味 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 46: return new LevelNoteCht{StageId="Map02_05h",Name="座間味 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 47: return new LevelNoteCht{StageId="Map02_06e",Name="座間味 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 48: return new LevelNoteCht{StageId="Map02_06n",Name="座間味 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 49: return new LevelNoteCht{StageId="Map02_06h",Name="座間味 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Wake up Loser"};
case 50: return new LevelNoteCht{StageId="Map02_07e",Name="座間味 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 51: return new LevelNoteCht{StageId="Map02_07n",Name="座間味 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 52: return new LevelNoteCht{StageId="Map02_07h",Name="座間味 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 53: return new LevelNoteCht{StageId="Map02_08e",Name="座間味 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 54: return new LevelNoteCht{StageId="Map02_08n",Name="座間味 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 55: return new LevelNoteCht{StageId="Map02_08h",Name="座間味 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 56: return new LevelNoteCht{StageId="Map02_09e",Name="座間味 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 57: return new LevelNoteCht{StageId="Map02_09n",Name="座間味 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 58: return new LevelNoteCht{StageId="Map02_09h",Name="座間味 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="掠日彗星"};
case 59: return new LevelNoteCht{StageId="Map02_10e",Name="座間味 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="情緒來了"};
case 60: return new LevelNoteCht{StageId="Map02_10n",Name="座間味 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="情緒來了"};
case 61: return new LevelNoteCht{StageId="Map02_10h",Name="座間味 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="情緒來了"};
case 62: return new LevelNoteCht{StageId="Map03_01e",Name="渡嘉敷 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 63: return new LevelNoteCht{StageId="Map03_01n",Name="渡嘉敷 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 64: return new LevelNoteCht{StageId="Map03_01h",Name="渡嘉敷 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 65: return new LevelNoteCht{StageId="Map03_02e",Name="渡嘉敷 關卡 02",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 66: return new LevelNoteCht{StageId="Map03_02n",Name="渡嘉敷 關卡 02",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 67: return new LevelNoteCht{StageId="Map03_02h",Name="渡嘉敷 關卡 02",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 68: return new LevelNoteCht{StageId="Map03_03e",Name="渡嘉敷 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 69: return new LevelNoteCht{StageId="Map03_03n",Name="渡嘉敷 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 70: return new LevelNoteCht{StageId="Map03_03h",Name="渡嘉敷 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="Hope popo"};
case 71: return new LevelNoteCht{StageId="Map03_04e",Name="渡嘉敷 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 72: return new LevelNoteCht{StageId="Map03_04n",Name="渡嘉敷 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 73: return new LevelNoteCht{StageId="Map03_04h",Name="渡嘉敷 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 74: return new LevelNoteCht{StageId="Map03_05e",Name="渡嘉敷 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 75: return new LevelNoteCht{StageId="Map03_05n",Name="渡嘉敷 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 76: return new LevelNoteCht{StageId="Map03_05h",Name="渡嘉敷 關卡 05",TextGameMode="對戰模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 77: return new LevelNoteCht{StageId="Map03_06e",Name="渡嘉敷 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 78: return new LevelNoteCht{StageId="Map03_06n",Name="渡嘉敷 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 79: return new LevelNoteCht{StageId="Map03_06h",Name="渡嘉敷 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 80: return new LevelNoteCht{StageId="Map03_07e",Name="渡嘉敷 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 81: return new LevelNoteCht{StageId="Map03_07n",Name="渡嘉敷 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 82: return new LevelNoteCht{StageId="Map03_07h",Name="渡嘉敷 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 83: return new LevelNoteCht{StageId="Map03_08e",Name="渡嘉敷 關卡 08",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 84: return new LevelNoteCht{StageId="Map03_08n",Name="渡嘉敷 關卡 08",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 85: return new LevelNoteCht{StageId="Map03_08h",Name="渡嘉敷 關卡 08",TextGameMode="對戰模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 86: return new LevelNoteCht{StageId="Map03_09e",Name="渡嘉敷 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 87: return new LevelNoteCht{StageId="Map03_09n",Name="渡嘉敷 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 88: return new LevelNoteCht{StageId="Map03_09h",Name="渡嘉敷 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="滿奇"};
case 89: return new LevelNoteCht{StageId="Map03_10e",Name="渡嘉敷 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="孥克的詭計"};
case 90: return new LevelNoteCht{StageId="Map03_10n",Name="渡嘉敷 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="孥克的詭計"};
case 91: return new LevelNoteCht{StageId="Map03_10h",Name="渡嘉敷 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="林瑪黛",TextSongTitle="孥克的詭計"};
case 92: return new LevelNoteCht{StageId="Map04_01e",Name="台鹼宿舍 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 93: return new LevelNoteCht{StageId="Map04_01n",Name="台鹼宿舍 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 94: return new LevelNoteCht{StageId="Map04_01h",Name="台鹼宿舍 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 95: return new LevelNoteCht{StageId="Map04_02e",Name="台鹼宿舍 關卡 02",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 96: return new LevelNoteCht{StageId="Map04_02n",Name="台鹼宿舍 關卡 02",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 97: return new LevelNoteCht{StageId="Map04_02h",Name="台鹼宿舍 關卡 02",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 98: return new LevelNoteCht{StageId="Map04_03e",Name="台鹼宿舍 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 99: return new LevelNoteCht{StageId="Map04_03n",Name="台鹼宿舍 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 100: return new LevelNoteCht{StageId="Map04_03h",Name="台鹼宿舍 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="滿足背後"};
case 101: return new LevelNoteCht{StageId="Map04_04e",Name="台鹼宿舍 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 102: return new LevelNoteCht{StageId="Map04_04n",Name="台鹼宿舍 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 103: return new LevelNoteCht{StageId="Map04_04h",Name="台鹼宿舍 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 104: return new LevelNoteCht{StageId="Map04_05e",Name="台鹼宿舍 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 105: return new LevelNoteCht{StageId="Map04_05n",Name="台鹼宿舍 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 106: return new LevelNoteCht{StageId="Map04_05h",Name="台鹼宿舍 關卡 05",TextGameMode="對戰模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 107: return new LevelNoteCht{StageId="Map04_06e",Name="台鹼宿舍 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 108: return new LevelNoteCht{StageId="Map04_06n",Name="台鹼宿舍 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 109: return new LevelNoteCht{StageId="Map04_06h",Name="台鹼宿舍 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="達子",TextSongTitle="Hello"};
case 110: return new LevelNoteCht{StageId="Map04_07e",Name="台鹼宿舍 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 111: return new LevelNoteCht{StageId="Map04_07n",Name="台鹼宿舍 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 112: return new LevelNoteCht{StageId="Map04_07h",Name="台鹼宿舍 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 113: return new LevelNoteCht{StageId="Map04_08e",Name="台鹼宿舍 關卡 08",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 114: return new LevelNoteCht{StageId="Map04_08n",Name="台鹼宿舍 關卡 08",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 115: return new LevelNoteCht{StageId="Map04_08h",Name="台鹼宿舍 關卡 08",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 116: return new LevelNoteCht{StageId="Map04_09e",Name="台鹼宿舍 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 117: return new LevelNoteCht{StageId="Map04_09n",Name="台鹼宿舍 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 118: return new LevelNoteCht{StageId="Map04_09h",Name="台鹼宿舍 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="如果愛有那麼徹底"};
case 119: return new LevelNoteCht{StageId="Map04_10e",Name="台鹼宿舍 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="真的很真"};
case 120: return new LevelNoteCht{StageId="Map04_10n",Name="台鹼宿舍 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="真的很真"};
case 121: return new LevelNoteCht{StageId="Map04_10h",Name="台鹼宿舍 關卡 10",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="真的很真"};
case 122: return new LevelNoteCht{StageId="MapS1_01e",Name="澎湖 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 123: return new LevelNoteCht{StageId="MapS1_01n",Name="澎湖 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 124: return new LevelNoteCht{StageId="MapS1_01h",Name="澎湖 關卡 01",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 125: return new LevelNoteCht{StageId="MapS1_02e",Name="澎湖 關卡 02",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 126: return new LevelNoteCht{StageId="MapS1_02n",Name="澎湖 關卡 02",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 127: return new LevelNoteCht{StageId="MapS1_02h",Name="澎湖 關卡 02",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 128: return new LevelNoteCht{StageId="MapS1_03e",Name="澎湖 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 129: return new LevelNoteCht{StageId="MapS1_03n",Name="澎湖 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 130: return new LevelNoteCht{StageId="MapS1_03h",Name="澎湖 關卡 03",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵電感應"};
case 131: return new LevelNoteCht{StageId="MapS1_04e",Name="澎湖 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 132: return new LevelNoteCht{StageId="MapS1_04n",Name="澎湖 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 133: return new LevelNoteCht{StageId="MapS1_04h",Name="澎湖 關卡 04",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 134: return new LevelNoteCht{StageId="MapS1_05e",Name="澎湖 關卡 05",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 135: return new LevelNoteCht{StageId="MapS1_05n",Name="澎湖 關卡 05",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 136: return new LevelNoteCht{StageId="MapS1_05h",Name="澎湖 關卡 05",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 137: return new LevelNoteCht{StageId="MapS1_06e",Name="澎湖 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 138: return new LevelNoteCht{StageId="MapS1_06n",Name="澎湖 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 139: return new LevelNoteCht{StageId="MapS1_06h",Name="澎湖 關卡 06",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="莫名其妙的喵"};
case 140: return new LevelNoteCht{StageId="MapS1_07e",Name="澎湖 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 141: return new LevelNoteCht{StageId="MapS1_07n",Name="澎湖 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 142: return new LevelNoteCht{StageId="MapS1_07h",Name="澎湖 關卡 07",TextGameMode="跳舞模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 143: return new LevelNoteCht{StageId="MapS1_08e",Name="澎湖 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 144: return new LevelNoteCht{StageId="MapS1_08n",Name="澎湖 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 145: return new LevelNoteCht{StageId="MapS1_08h",Name="澎湖 關卡 08",TextGameMode="對戰模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 146: return new LevelNoteCht{StageId="MapS1_09e",Name="澎湖 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 147: return new LevelNoteCht{StageId="MapS1_09n",Name="澎湖 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 148: return new LevelNoteCht{StageId="MapS1_09h",Name="澎湖 關卡 09",TextGameMode="跑酷模式",TextArtistTitle="王舜",TextSongTitle="喵電感應 王舜Remix"};
case 149: return new LevelNoteCht{StageId="MapS1_10e",Name="澎湖 關卡 10",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 150: return new LevelNoteCht{StageId="MapS1_10n",Name="澎湖 關卡 10",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 151: return new LevelNoteCht{StageId="MapS1_10h",Name="澎湖 關卡 10",TextGameMode="跳舞模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 152: return new LevelNoteCht{StageId="MapS1_11e",Name="澎湖 關卡 11",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 153: return new LevelNoteCht{StageId="MapS1_11n",Name="澎湖 關卡 11",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 154: return new LevelNoteCht{StageId="MapS1_11h",Name="澎湖 關卡 11",TextGameMode="對戰模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 155: return new LevelNoteCht{StageId="MapS1_12e",Name="澎湖 關卡 12",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 156: return new LevelNoteCht{StageId="MapS1_12n",Name="澎湖 關卡 12",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 157: return new LevelNoteCht{StageId="MapS1_12h",Name="澎湖 關卡 12",TextGameMode="跑酷模式",TextArtistTitle="勸世寶貝喵喵",TextSongTitle="喵喵的異次元"};
case 158: return new LevelNoteCht{StageId="MapS1_13e",Name="澎湖 關卡 13",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 159: return new LevelNoteCht{StageId="MapS1_13n",Name="澎湖 關卡 13",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 160: return new LevelNoteCht{StageId="MapS1_13h",Name="澎湖 關卡 13",TextGameMode="跳舞模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 161: return new LevelNoteCht{StageId="MapS1_14e",Name="澎湖 關卡 14",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 162: return new LevelNoteCht{StageId="MapS1_14n",Name="澎湖 關卡 14",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 163: return new LevelNoteCht{StageId="MapS1_14h",Name="澎湖 關卡 14",TextGameMode="對戰模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 164: return new LevelNoteCht{StageId="MapS1_15e",Name="澎湖 關卡 15",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 165: return new LevelNoteCht{StageId="MapS1_15n",Name="澎湖 關卡 15",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};
case 166: return new LevelNoteCht{StageId="MapS1_15h",Name="澎湖 關卡 15",TextGameMode="跑酷模式",TextArtistTitle="丁繼",TextSongTitle="喵電感應 丁繼Remix"};

			default:
				throw new UnityException ("沒有這個定義:"+key);
			}
		}
	}
}