using UnityEngine;
namespace Remix{
	public class LevelNoteEng{
		public const int ID_COUNT = 167;

		public string StageId {get; set;}
public string Name {get; set;}
public string TextGameMode {get; set;}
public string TextArtistTitle {get; set;}
public string TextSongTitle {get; set;}

		public static LevelNoteEng Get(string key){
			switch (key) {
			case "Map01_00n": return new LevelNoteEng{StageId="Map01_00n",Name="Tutorial",TextGameMode="Tutorial"};
case "Map01_0An": return new LevelNoteEng{StageId="Map01_0An",Name="SYNC",TextGameMode="SYNC"};
case "Map01_01e": return new LevelNoteEng{StageId="Map01_01e",Name="Houton Level 01",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_01n": return new LevelNoteEng{StageId="Map01_01n",Name="Houton Level 01",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_01h": return new LevelNoteEng{StageId="Map01_01h",Name="Houton Level 01",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_02e": return new LevelNoteEng{StageId="Map01_02e",Name="Houton Level 02",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_02n": return new LevelNoteEng{StageId="Map01_02n",Name="Houton Level 02",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_02h": return new LevelNoteEng{StageId="Map01_02h",Name="Houton Level 02",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_03e": return new LevelNoteEng{StageId="Map01_03e",Name="Houton Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_03n": return new LevelNoteEng{StageId="Map01_03n",Name="Houton Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_03h": return new LevelNoteEng{StageId="Map01_03h",Name="Houton Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case "Map01_04e": return new LevelNoteEng{StageId="Map01_04e",Name="Houton Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_04n": return new LevelNoteEng{StageId="Map01_04n",Name="Houton Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_04h": return new LevelNoteEng{StageId="Map01_04h",Name="Houton Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_05e": return new LevelNoteEng{StageId="Map01_05e",Name="Houton Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_05n": return new LevelNoteEng{StageId="Map01_05n",Name="Houton Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_05h": return new LevelNoteEng{StageId="Map01_05h",Name="Houton Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_06e": return new LevelNoteEng{StageId="Map01_06e",Name="Houton Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_06n": return new LevelNoteEng{StageId="Map01_06n",Name="Houton Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_06h": return new LevelNoteEng{StageId="Map01_06h",Name="Houton Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case "Map01_07e": return new LevelNoteEng{StageId="Map01_07e",Name="Houton Level 07",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_07n": return new LevelNoteEng{StageId="Map01_07n",Name="Houton Level 07",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_07h": return new LevelNoteEng{StageId="Map01_07h",Name="Houton Level 07",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_08e": return new LevelNoteEng{StageId="Map01_08e",Name="Houton Level 08",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_08n": return new LevelNoteEng{StageId="Map01_08n",Name="Houton Level 08",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_08h": return new LevelNoteEng{StageId="Map01_08h",Name="Houton Level 08",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_09e": return new LevelNoteEng{StageId="Map01_09e",Name="Houton Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_09n": return new LevelNoteEng{StageId="Map01_09n",Name="Houton Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_09h": return new LevelNoteEng{StageId="Map01_09h",Name="Houton Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case "Map01_10e": return new LevelNoteEng{StageId="Map01_10e",Name="Houton Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case "Map01_10n": return new LevelNoteEng{StageId="Map01_10n",Name="Houton Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case "Map01_10h": return new LevelNoteEng{StageId="Map01_10h",Name="Houton Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case "Map02_01e": return new LevelNoteEng{StageId="Map02_01e",Name="Zamami Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_01n": return new LevelNoteEng{StageId="Map02_01n",Name="Zamami Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_01h": return new LevelNoteEng{StageId="Map02_01h",Name="Zamami Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_02e": return new LevelNoteEng{StageId="Map02_02e",Name="Zamami Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_02n": return new LevelNoteEng{StageId="Map02_02n",Name="Zamami Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_02h": return new LevelNoteEng{StageId="Map02_02h",Name="Zamami Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_03e": return new LevelNoteEng{StageId="Map02_03e",Name="Zamami Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_03n": return new LevelNoteEng{StageId="Map02_03n",Name="Zamami Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_03h": return new LevelNoteEng{StageId="Map02_03h",Name="Zamami Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case "Map02_04e": return new LevelNoteEng{StageId="Map02_04e",Name="Zamami Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_04n": return new LevelNoteEng{StageId="Map02_04n",Name="Zamami Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_04h": return new LevelNoteEng{StageId="Map02_04h",Name="Zamami Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_05e": return new LevelNoteEng{StageId="Map02_05e",Name="Zamami Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_05n": return new LevelNoteEng{StageId="Map02_05n",Name="Zamami Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_05h": return new LevelNoteEng{StageId="Map02_05h",Name="Zamami Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_06e": return new LevelNoteEng{StageId="Map02_06e",Name="Zamami Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_06n": return new LevelNoteEng{StageId="Map02_06n",Name="Zamami Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_06h": return new LevelNoteEng{StageId="Map02_06h",Name="Zamami Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case "Map02_07e": return new LevelNoteEng{StageId="Map02_07e",Name="Zamami Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_07n": return new LevelNoteEng{StageId="Map02_07n",Name="Zamami Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_07h": return new LevelNoteEng{StageId="Map02_07h",Name="Zamami Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_08e": return new LevelNoteEng{StageId="Map02_08e",Name="Zamami Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_08n": return new LevelNoteEng{StageId="Map02_08n",Name="Zamami Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_08h": return new LevelNoteEng{StageId="Map02_08h",Name="Zamami Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_09e": return new LevelNoteEng{StageId="Map02_09e",Name="Zamami Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_09n": return new LevelNoteEng{StageId="Map02_09n",Name="Zamami Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_09h": return new LevelNoteEng{StageId="Map02_09h",Name="Zamami Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case "Map02_10e": return new LevelNoteEng{StageId="Map02_10e",Name="Zamami Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="情緒來了"};
case "Map02_10n": return new LevelNoteEng{StageId="Map02_10n",Name="Zamami Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="情緒來了"};
case "Map02_10h": return new LevelNoteEng{StageId="Map02_10h",Name="Zamami Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="情緒來了"};
case "Map03_01e": return new LevelNoteEng{StageId="Map03_01e",Name="Tokashiki Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_01n": return new LevelNoteEng{StageId="Map03_01n",Name="Tokashiki Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_01h": return new LevelNoteEng{StageId="Map03_01h",Name="Tokashiki Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_02e": return new LevelNoteEng{StageId="Map03_02e",Name="Tokashiki Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_02n": return new LevelNoteEng{StageId="Map03_02n",Name="Tokashiki Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_02h": return new LevelNoteEng{StageId="Map03_02h",Name="Tokashiki Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_03e": return new LevelNoteEng{StageId="Map03_03e",Name="Tokashiki Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_03n": return new LevelNoteEng{StageId="Map03_03n",Name="Tokashiki Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_03h": return new LevelNoteEng{StageId="Map03_03h",Name="Tokashiki Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case "Map03_04e": return new LevelNoteEng{StageId="Map03_04e",Name="Tokashiki Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_04n": return new LevelNoteEng{StageId="Map03_04n",Name="Tokashiki Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_04h": return new LevelNoteEng{StageId="Map03_04h",Name="Tokashiki Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_05e": return new LevelNoteEng{StageId="Map03_05e",Name="Tokashiki Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_05n": return new LevelNoteEng{StageId="Map03_05n",Name="Tokashiki Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_05h": return new LevelNoteEng{StageId="Map03_05h",Name="Tokashiki Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_06e": return new LevelNoteEng{StageId="Map03_06e",Name="Tokashiki Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_06n": return new LevelNoteEng{StageId="Map03_06n",Name="Tokashiki Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_06h": return new LevelNoteEng{StageId="Map03_06h",Name="Tokashiki Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case "Map03_07e": return new LevelNoteEng{StageId="Map03_07e",Name="Tokashiki Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_07n": return new LevelNoteEng{StageId="Map03_07n",Name="Tokashiki Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_07h": return new LevelNoteEng{StageId="Map03_07h",Name="Tokashiki Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_08e": return new LevelNoteEng{StageId="Map03_08e",Name="Tokashiki Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_08n": return new LevelNoteEng{StageId="Map03_08n",Name="Tokashiki Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_08h": return new LevelNoteEng{StageId="Map03_08h",Name="Tokashiki Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_09e": return new LevelNoteEng{StageId="Map03_09e",Name="Tokashiki Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_09n": return new LevelNoteEng{StageId="Map03_09n",Name="Tokashiki Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_09h": return new LevelNoteEng{StageId="Map03_09h",Name="Tokashiki Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case "Map03_10e": return new LevelNoteEng{StageId="Map03_10e",Name="Tokashiki Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="孥克的詭計"};
case "Map03_10n": return new LevelNoteEng{StageId="Map03_10n",Name="Tokashiki Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="孥克的詭計"};
case "Map03_10h": return new LevelNoteEng{StageId="Map03_10h",Name="Tokashiki Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="孥克的詭計"};
case "Map04_01e": return new LevelNoteEng{StageId="Map04_01e",Name="Dorm of CPDC Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_01n": return new LevelNoteEng{StageId="Map04_01n",Name="Dorm of CPDC Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_01h": return new LevelNoteEng{StageId="Map04_01h",Name="Dorm of CPDC Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_02e": return new LevelNoteEng{StageId="Map04_02e",Name="Dorm of CPDC Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_02n": return new LevelNoteEng{StageId="Map04_02n",Name="Dorm of CPDC Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_02h": return new LevelNoteEng{StageId="Map04_02h",Name="Dorm of CPDC Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_03e": return new LevelNoteEng{StageId="Map04_03e",Name="Dorm of CPDC Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_03n": return new LevelNoteEng{StageId="Map04_03n",Name="Dorm of CPDC Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_03h": return new LevelNoteEng{StageId="Map04_03h",Name="Dorm of CPDC Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case "Map04_04e": return new LevelNoteEng{StageId="Map04_04e",Name="Dorm of CPDC Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_04n": return new LevelNoteEng{StageId="Map04_04n",Name="Dorm of CPDC Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_04h": return new LevelNoteEng{StageId="Map04_04h",Name="Dorm of CPDC Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_05e": return new LevelNoteEng{StageId="Map04_05e",Name="Dorm of CPDC Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_05n": return new LevelNoteEng{StageId="Map04_05n",Name="Dorm of CPDC Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_05h": return new LevelNoteEng{StageId="Map04_05h",Name="Dorm of CPDC Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_06e": return new LevelNoteEng{StageId="Map04_06e",Name="Dorm of CPDC Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_06n": return new LevelNoteEng{StageId="Map04_06n",Name="Dorm of CPDC Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_06h": return new LevelNoteEng{StageId="Map04_06h",Name="Dorm of CPDC Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case "Map04_07e": return new LevelNoteEng{StageId="Map04_07e",Name="Dorm of CPDC Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_07n": return new LevelNoteEng{StageId="Map04_07n",Name="Dorm of CPDC Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_07h": return new LevelNoteEng{StageId="Map04_07h",Name="Dorm of CPDC Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_08e": return new LevelNoteEng{StageId="Map04_08e",Name="Dorm of CPDC Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_08n": return new LevelNoteEng{StageId="Map04_08n",Name="Dorm of CPDC Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_08h": return new LevelNoteEng{StageId="Map04_08h",Name="Dorm of CPDC Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_09e": return new LevelNoteEng{StageId="Map04_09e",Name="Dorm of CPDC Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_09n": return new LevelNoteEng{StageId="Map04_09n",Name="Dorm of CPDC Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_09h": return new LevelNoteEng{StageId="Map04_09h",Name="Dorm of CPDC Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case "Map04_10e": return new LevelNoteEng{StageId="Map04_10e",Name="Dorm of CPDC Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="真的很真"};
case "Map04_10n": return new LevelNoteEng{StageId="Map04_10n",Name="Dorm of CPDC Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="真的很真"};
case "Map04_10h": return new LevelNoteEng{StageId="Map04_10h",Name="Dorm of CPDC Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="真的很真"};
case "MapS1_01e": return new LevelNoteEng{StageId="MapS1_01e",Name="Penghu Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_01n": return new LevelNoteEng{StageId="MapS1_01n",Name="Penghu Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_01h": return new LevelNoteEng{StageId="MapS1_01h",Name="Penghu Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_02e": return new LevelNoteEng{StageId="MapS1_02e",Name="Penghu Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_02n": return new LevelNoteEng{StageId="MapS1_02n",Name="Penghu Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_02h": return new LevelNoteEng{StageId="MapS1_02h",Name="Penghu Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_03e": return new LevelNoteEng{StageId="MapS1_03e",Name="Penghu Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_03n": return new LevelNoteEng{StageId="MapS1_03n",Name="Penghu Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_03h": return new LevelNoteEng{StageId="MapS1_03h",Name="Penghu Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case "MapS1_04e": return new LevelNoteEng{StageId="MapS1_04e",Name="Penghu Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_04n": return new LevelNoteEng{StageId="MapS1_04n",Name="Penghu Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_04h": return new LevelNoteEng{StageId="MapS1_04h",Name="Penghu Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_05e": return new LevelNoteEng{StageId="MapS1_05e",Name="Penghu Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_05n": return new LevelNoteEng{StageId="MapS1_05n",Name="Penghu Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_05h": return new LevelNoteEng{StageId="MapS1_05h",Name="Penghu Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_06e": return new LevelNoteEng{StageId="MapS1_06e",Name="Penghu Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_06n": return new LevelNoteEng{StageId="MapS1_06n",Name="Penghu Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_06h": return new LevelNoteEng{StageId="MapS1_06h",Name="Penghu Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case "MapS1_07e": return new LevelNoteEng{StageId="MapS1_07e",Name="Penghu Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_07n": return new LevelNoteEng{StageId="MapS1_07n",Name="Penghu Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_07h": return new LevelNoteEng{StageId="MapS1_07h",Name="Penghu Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_08e": return new LevelNoteEng{StageId="MapS1_08e",Name="Penghu Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_08n": return new LevelNoteEng{StageId="MapS1_08n",Name="Penghu Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_08h": return new LevelNoteEng{StageId="MapS1_08h",Name="Penghu Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_09e": return new LevelNoteEng{StageId="MapS1_09e",Name="Penghu Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_09n": return new LevelNoteEng{StageId="MapS1_09n",Name="Penghu Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_09h": return new LevelNoteEng{StageId="MapS1_09h",Name="Penghu Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case "MapS1_10e": return new LevelNoteEng{StageId="MapS1_10e",Name="Penghu Level 10",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_10n": return new LevelNoteEng{StageId="MapS1_10n",Name="Penghu Level 10",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_10h": return new LevelNoteEng{StageId="MapS1_10h",Name="Penghu Level 10",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_11e": return new LevelNoteEng{StageId="MapS1_11e",Name="Penghu Level 11",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_11n": return new LevelNoteEng{StageId="MapS1_11n",Name="Penghu Level 11",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_11h": return new LevelNoteEng{StageId="MapS1_11h",Name="Penghu Level 11",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_12e": return new LevelNoteEng{StageId="MapS1_12e",Name="Penghu Level 12",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_12n": return new LevelNoteEng{StageId="MapS1_12n",Name="Penghu Level 12",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_12h": return new LevelNoteEng{StageId="MapS1_12h",Name="Penghu Level 12",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case "MapS1_13e": return new LevelNoteEng{StageId="MapS1_13e",Name="Penghu Level 13",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_13n": return new LevelNoteEng{StageId="MapS1_13n",Name="Penghu Level 13",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_13h": return new LevelNoteEng{StageId="MapS1_13h",Name="Penghu Level 13",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_14e": return new LevelNoteEng{StageId="MapS1_14e",Name="Penghu Level 14",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_14n": return new LevelNoteEng{StageId="MapS1_14n",Name="Penghu Level 14",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_14h": return new LevelNoteEng{StageId="MapS1_14h",Name="Penghu Level 14",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_15e": return new LevelNoteEng{StageId="MapS1_15e",Name="Penghu Level 15",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_15n": return new LevelNoteEng{StageId="MapS1_15n",Name="Penghu Level 15",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case "MapS1_15h": return new LevelNoteEng{StageId="MapS1_15h",Name="Penghu Level 15",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};

			default:
				throw new UnityException ("沒有這個定義:"+key);
			}
		}

		public static LevelNoteEng Get(int key){
			switch (key) {
			case 0: return new LevelNoteEng{StageId="Map01_00n",Name="Tutorial",TextGameMode="Tutorial"};
case 1: return new LevelNoteEng{StageId="Map01_0An",Name="SYNC",TextGameMode="SYNC"};
case 2: return new LevelNoteEng{StageId="Map01_01e",Name="Houton Level 01",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 3: return new LevelNoteEng{StageId="Map01_01n",Name="Houton Level 01",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 4: return new LevelNoteEng{StageId="Map01_01h",Name="Houton Level 01",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 5: return new LevelNoteEng{StageId="Map01_02e",Name="Houton Level 02",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 6: return new LevelNoteEng{StageId="Map01_02n",Name="Houton Level 02",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 7: return new LevelNoteEng{StageId="Map01_02h",Name="Houton Level 02",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 8: return new LevelNoteEng{StageId="Map01_03e",Name="Houton Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 9: return new LevelNoteEng{StageId="Map01_03n",Name="Houton Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 10: return new LevelNoteEng{StageId="Map01_03h",Name="Houton Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="喵喵頌"};
case 11: return new LevelNoteEng{StageId="Map01_04e",Name="Houton Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 12: return new LevelNoteEng{StageId="Map01_04n",Name="Houton Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 13: return new LevelNoteEng{StageId="Map01_04h",Name="Houton Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 14: return new LevelNoteEng{StageId="Map01_05e",Name="Houton Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 15: return new LevelNoteEng{StageId="Map01_05n",Name="Houton Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 16: return new LevelNoteEng{StageId="Map01_05h",Name="Houton Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 17: return new LevelNoteEng{StageId="Map01_06e",Name="Houton Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 18: return new LevelNoteEng{StageId="Map01_06n",Name="Houton Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 19: return new LevelNoteEng{StageId="Map01_06h",Name="Houton Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Summer dreamin"};
case 20: return new LevelNoteEng{StageId="Map01_07e",Name="Houton Level 07",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 21: return new LevelNoteEng{StageId="Map01_07n",Name="Houton Level 07",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 22: return new LevelNoteEng{StageId="Map01_07h",Name="Houton Level 07",TextGameMode="Dancing Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 23: return new LevelNoteEng{StageId="Map01_08e",Name="Houton Level 08",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 24: return new LevelNoteEng{StageId="Map01_08n",Name="Houton Level 08",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 25: return new LevelNoteEng{StageId="Map01_08h",Name="Houton Level 08",TextGameMode="Fighting Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 26: return new LevelNoteEng{StageId="Map01_09e",Name="Houton Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 27: return new LevelNoteEng{StageId="Map01_09n",Name="Houton Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 28: return new LevelNoteEng{StageId="Map01_09h",Name="Houton Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="無所遁形的貓"};
case 29: return new LevelNoteEng{StageId="Map01_10e",Name="Houton Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case 30: return new LevelNoteEng{StageId="Map01_10n",Name="Houton Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case 31: return new LevelNoteEng{StageId="Map01_10h",Name="Houton Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="MUSDM",TextSongTitle="Call me queen"};
case 32: return new LevelNoteEng{StageId="Map02_01e",Name="Zamami Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 33: return new LevelNoteEng{StageId="Map02_01n",Name="Zamami Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 34: return new LevelNoteEng{StageId="Map02_01h",Name="Zamami Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 35: return new LevelNoteEng{StageId="Map02_02e",Name="Zamami Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 36: return new LevelNoteEng{StageId="Map02_02n",Name="Zamami Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 37: return new LevelNoteEng{StageId="Map02_02h",Name="Zamami Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 38: return new LevelNoteEng{StageId="Map02_03e",Name="Zamami Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 39: return new LevelNoteEng{StageId="Map02_03n",Name="Zamami Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 40: return new LevelNoteEng{StageId="Map02_03h",Name="Zamami Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="全壘打"};
case 41: return new LevelNoteEng{StageId="Map02_04e",Name="Zamami Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 42: return new LevelNoteEng{StageId="Map02_04n",Name="Zamami Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 43: return new LevelNoteEng{StageId="Map02_04h",Name="Zamami Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 44: return new LevelNoteEng{StageId="Map02_05e",Name="Zamami Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 45: return new LevelNoteEng{StageId="Map02_05n",Name="Zamami Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 46: return new LevelNoteEng{StageId="Map02_05h",Name="Zamami Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 47: return new LevelNoteEng{StageId="Map02_06e",Name="Zamami Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 48: return new LevelNoteEng{StageId="Map02_06n",Name="Zamami Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 49: return new LevelNoteEng{StageId="Map02_06h",Name="Zamami Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Wake up Loser"};
case 50: return new LevelNoteEng{StageId="Map02_07e",Name="Zamami Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 51: return new LevelNoteEng{StageId="Map02_07n",Name="Zamami Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 52: return new LevelNoteEng{StageId="Map02_07h",Name="Zamami Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 53: return new LevelNoteEng{StageId="Map02_08e",Name="Zamami Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 54: return new LevelNoteEng{StageId="Map02_08n",Name="Zamami Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 55: return new LevelNoteEng{StageId="Map02_08h",Name="Zamami Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 56: return new LevelNoteEng{StageId="Map02_09e",Name="Zamami Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 57: return new LevelNoteEng{StageId="Map02_09n",Name="Zamami Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 58: return new LevelNoteEng{StageId="Map02_09h",Name="Zamami Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="掠日彗星"};
case 59: return new LevelNoteEng{StageId="Map02_10e",Name="Zamami Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="情緒來了"};
case 60: return new LevelNoteEng{StageId="Map02_10n",Name="Zamami Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="情緒來了"};
case 61: return new LevelNoteEng{StageId="Map02_10h",Name="Zamami Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Wang Shun",TextSongTitle="情緒來了"};
case 62: return new LevelNoteEng{StageId="Map03_01e",Name="Tokashiki Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 63: return new LevelNoteEng{StageId="Map03_01n",Name="Tokashiki Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 64: return new LevelNoteEng{StageId="Map03_01h",Name="Tokashiki Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 65: return new LevelNoteEng{StageId="Map03_02e",Name="Tokashiki Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 66: return new LevelNoteEng{StageId="Map03_02n",Name="Tokashiki Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 67: return new LevelNoteEng{StageId="Map03_02h",Name="Tokashiki Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 68: return new LevelNoteEng{StageId="Map03_03e",Name="Tokashiki Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 69: return new LevelNoteEng{StageId="Map03_03n",Name="Tokashiki Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 70: return new LevelNoteEng{StageId="Map03_03h",Name="Tokashiki Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="Hope popo"};
case 71: return new LevelNoteEng{StageId="Map03_04e",Name="Tokashiki Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 72: return new LevelNoteEng{StageId="Map03_04n",Name="Tokashiki Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 73: return new LevelNoteEng{StageId="Map03_04h",Name="Tokashiki Level 04",TextGameMode="Dancing Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 74: return new LevelNoteEng{StageId="Map03_05e",Name="Tokashiki Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 75: return new LevelNoteEng{StageId="Map03_05n",Name="Tokashiki Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 76: return new LevelNoteEng{StageId="Map03_05h",Name="Tokashiki Level 05",TextGameMode="Fighting Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 77: return new LevelNoteEng{StageId="Map03_06e",Name="Tokashiki Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 78: return new LevelNoteEng{StageId="Map03_06n",Name="Tokashiki Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 79: return new LevelNoteEng{StageId="Map03_06h",Name="Tokashiki Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="mGee",TextSongTitle="Atlantic state of mind"};
case 80: return new LevelNoteEng{StageId="Map03_07e",Name="Tokashiki Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 81: return new LevelNoteEng{StageId="Map03_07n",Name="Tokashiki Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 82: return new LevelNoteEng{StageId="Map03_07h",Name="Tokashiki Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 83: return new LevelNoteEng{StageId="Map03_08e",Name="Tokashiki Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 84: return new LevelNoteEng{StageId="Map03_08n",Name="Tokashiki Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 85: return new LevelNoteEng{StageId="Map03_08h",Name="Tokashiki Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 86: return new LevelNoteEng{StageId="Map03_09e",Name="Tokashiki Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 87: return new LevelNoteEng{StageId="Map03_09n",Name="Tokashiki Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 88: return new LevelNoteEng{StageId="Map03_09h",Name="Tokashiki Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="滿奇"};
case 89: return new LevelNoteEng{StageId="Map03_10e",Name="Tokashiki Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="孥克的詭計"};
case 90: return new LevelNoteEng{StageId="Map03_10n",Name="Tokashiki Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="孥克的詭計"};
case 91: return new LevelNoteEng{StageId="Map03_10h",Name="Tokashiki Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Ma-te-Lin",TextSongTitle="孥克的詭計"};
case 92: return new LevelNoteEng{StageId="Map04_01e",Name="Dorm of CPDC Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 93: return new LevelNoteEng{StageId="Map04_01n",Name="Dorm of CPDC Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 94: return new LevelNoteEng{StageId="Map04_01h",Name="Dorm of CPDC Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 95: return new LevelNoteEng{StageId="Map04_02e",Name="Dorm of CPDC Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 96: return new LevelNoteEng{StageId="Map04_02n",Name="Dorm of CPDC Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 97: return new LevelNoteEng{StageId="Map04_02h",Name="Dorm of CPDC Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 98: return new LevelNoteEng{StageId="Map04_03e",Name="Dorm of CPDC Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 99: return new LevelNoteEng{StageId="Map04_03n",Name="Dorm of CPDC Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 100: return new LevelNoteEng{StageId="Map04_03h",Name="Dorm of CPDC Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="滿足背後"};
case 101: return new LevelNoteEng{StageId="Map04_04e",Name="Dorm of CPDC Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 102: return new LevelNoteEng{StageId="Map04_04n",Name="Dorm of CPDC Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 103: return new LevelNoteEng{StageId="Map04_04h",Name="Dorm of CPDC Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 104: return new LevelNoteEng{StageId="Map04_05e",Name="Dorm of CPDC Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 105: return new LevelNoteEng{StageId="Map04_05n",Name="Dorm of CPDC Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 106: return new LevelNoteEng{StageId="Map04_05h",Name="Dorm of CPDC Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 107: return new LevelNoteEng{StageId="Map04_06e",Name="Dorm of CPDC Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 108: return new LevelNoteEng{StageId="Map04_06n",Name="Dorm of CPDC Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 109: return new LevelNoteEng{StageId="Map04_06h",Name="Dorm of CPDC Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Duzs",TextSongTitle="Hello"};
case 110: return new LevelNoteEng{StageId="Map04_07e",Name="Dorm of CPDC Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 111: return new LevelNoteEng{StageId="Map04_07n",Name="Dorm of CPDC Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 112: return new LevelNoteEng{StageId="Map04_07h",Name="Dorm of CPDC Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 113: return new LevelNoteEng{StageId="Map04_08e",Name="Dorm of CPDC Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 114: return new LevelNoteEng{StageId="Map04_08n",Name="Dorm of CPDC Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 115: return new LevelNoteEng{StageId="Map04_08h",Name="Dorm of CPDC Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 116: return new LevelNoteEng{StageId="Map04_09e",Name="Dorm of CPDC Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 117: return new LevelNoteEng{StageId="Map04_09n",Name="Dorm of CPDC Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 118: return new LevelNoteEng{StageId="Map04_09h",Name="Dorm of CPDC Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="如果愛有那麼徹底"};
case 119: return new LevelNoteEng{StageId="Map04_10e",Name="Dorm of CPDC Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="真的很真"};
case 120: return new LevelNoteEng{StageId="Map04_10n",Name="Dorm of CPDC Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="真的很真"};
case 121: return new LevelNoteEng{StageId="Map04_10h",Name="Dorm of CPDC Level 10",TextGameMode="Parkouring Mode",TextArtistTitle="Stingie",TextSongTitle="真的很真"};
case 122: return new LevelNoteEng{StageId="MapS1_01e",Name="Penghu Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 123: return new LevelNoteEng{StageId="MapS1_01n",Name="Penghu Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 124: return new LevelNoteEng{StageId="MapS1_01h",Name="Penghu Level 01",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 125: return new LevelNoteEng{StageId="MapS1_02e",Name="Penghu Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 126: return new LevelNoteEng{StageId="MapS1_02n",Name="Penghu Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 127: return new LevelNoteEng{StageId="MapS1_02h",Name="Penghu Level 02",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 128: return new LevelNoteEng{StageId="MapS1_03e",Name="Penghu Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 129: return new LevelNoteEng{StageId="MapS1_03n",Name="Penghu Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 130: return new LevelNoteEng{StageId="MapS1_03h",Name="Penghu Level 03",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應"};
case 131: return new LevelNoteEng{StageId="MapS1_04e",Name="Penghu Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 132: return new LevelNoteEng{StageId="MapS1_04n",Name="Penghu Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 133: return new LevelNoteEng{StageId="MapS1_04h",Name="Penghu Level 04",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 134: return new LevelNoteEng{StageId="MapS1_05e",Name="Penghu Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 135: return new LevelNoteEng{StageId="MapS1_05n",Name="Penghu Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 136: return new LevelNoteEng{StageId="MapS1_05h",Name="Penghu Level 05",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 137: return new LevelNoteEng{StageId="MapS1_06e",Name="Penghu Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 138: return new LevelNoteEng{StageId="MapS1_06n",Name="Penghu Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 139: return new LevelNoteEng{StageId="MapS1_06h",Name="Penghu Level 06",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="莫名其妙的喵"};
case 140: return new LevelNoteEng{StageId="MapS1_07e",Name="Penghu Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 141: return new LevelNoteEng{StageId="MapS1_07n",Name="Penghu Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 142: return new LevelNoteEng{StageId="MapS1_07h",Name="Penghu Level 07",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 143: return new LevelNoteEng{StageId="MapS1_08e",Name="Penghu Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 144: return new LevelNoteEng{StageId="MapS1_08n",Name="Penghu Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 145: return new LevelNoteEng{StageId="MapS1_08h",Name="Penghu Level 08",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 146: return new LevelNoteEng{StageId="MapS1_09e",Name="Penghu Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 147: return new LevelNoteEng{StageId="MapS1_09n",Name="Penghu Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 148: return new LevelNoteEng{StageId="MapS1_09h",Name="Penghu Level 09",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Wang Shun Remix"};
case 149: return new LevelNoteEng{StageId="MapS1_10e",Name="Penghu Level 10",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 150: return new LevelNoteEng{StageId="MapS1_10n",Name="Penghu Level 10",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 151: return new LevelNoteEng{StageId="MapS1_10h",Name="Penghu Level 10",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 152: return new LevelNoteEng{StageId="MapS1_11e",Name="Penghu Level 11",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 153: return new LevelNoteEng{StageId="MapS1_11n",Name="Penghu Level 11",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 154: return new LevelNoteEng{StageId="MapS1_11h",Name="Penghu Level 11",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 155: return new LevelNoteEng{StageId="MapS1_12e",Name="Penghu Level 12",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 156: return new LevelNoteEng{StageId="MapS1_12n",Name="Penghu Level 12",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 157: return new LevelNoteEng{StageId="MapS1_12h",Name="Penghu Level 12",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵喵的異次元"};
case 158: return new LevelNoteEng{StageId="MapS1_13e",Name="Penghu Level 13",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 159: return new LevelNoteEng{StageId="MapS1_13n",Name="Penghu Level 13",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 160: return new LevelNoteEng{StageId="MapS1_13h",Name="Penghu Level 13",TextGameMode="Dancing Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 161: return new LevelNoteEng{StageId="MapS1_14e",Name="Penghu Level 14",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 162: return new LevelNoteEng{StageId="MapS1_14n",Name="Penghu Level 14",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 163: return new LevelNoteEng{StageId="MapS1_14h",Name="Penghu Level 14",TextGameMode="Fighting Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 164: return new LevelNoteEng{StageId="MapS1_15e",Name="Penghu Level 15",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 165: return new LevelNoteEng{StageId="MapS1_15n",Name="Penghu Level 15",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};
case 166: return new LevelNoteEng{StageId="MapS1_15h",Name="Penghu Level 15",TextGameMode="Parkouring Mode",TextArtistTitle="Trance Baby Meow",TextSongTitle="喵電感應 Stingie Remix"};

			default:
				throw new UnityException ("沒有這個定義:"+key);
			}
		}
	}
}